version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
      - npm install yarn
      - yarn --prod

  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
