export enum SocketActionType {
  CONTENT_UPDATE = 'CONTENT_UPDATE',
  ROUTE_CHANGE = 'ROUTE_CHANGE',
  CURSOR_LOCATION_CHANGE = 'CURSOR_LOCATION_CHANGE',
  EDITING_STATUS = 'EDITING_STATUS',
  USER_LIST_UPDATE = 'USER_LIST_UPDATE',
  PROPERTY_UPDATE = 'PROPERTY_UPDATE'
}
