export default {
  English: 'en',
  Arabic: 'ar',
  Azerbaijani: 'az',
  Chinese: 'zh',
  Czech: 'cs',
  Dutch: 'nl',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Hindi: 'hi',
  Hungarian: 'hu',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Polish: 'pl',
  Portuguese: 'pt',
  Russian: 'ru',
  Spanish: 'es',
  Swedish: 'sv',
  Turkish: 'tr',
  Ukranian: 'uk',
  Vietnamese: 'vi'
}
