name: Release Webapp
on:
  push:
    branches:
      - release

jobs:
  build_webapp:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --network-timeout 1000000 --frozen-lockfile

      - name: Build Webapp for Release
        run: yarn nx release webapp

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Release Artifacts to S3
        run: aws s3 sync ./dist/apps/webapp s3://mexit-monorepo-webapp
