name: Release Extension
on:
  push:
    branches:
      - release
      - automated-releases-extension

jobs:
  build_extension:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
      CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
      CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
      CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: Get Package Version
        id: get_package_version
        run: |
          content=`cat ./apps/extension/package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --network-timeout 1000000

      - name: Build Extension for Release
        run: yarn nx release extension

      - name: Zip Bundle
        working-directory: ./dist/apps/extension
        run: zip -r mexit-${{ fromJson(steps.get_package_version.outputs.packageJson).version }}.zip Assets background.js content.js index.html manifest.json

      - name: Create Release and Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ fromJson(steps.get_package_version.outputs.packageJson).version }}
          files: |
            dist/apps/extension/*.zip
      - name: Upload Zip to Chrome Store
        run: node apps/extension/build/upload-extension.mjs
      - name: Send Message to Slack with Zip
        run: node apps/extension/build/slack-message.mjs
 